# Generated by Django 5.0.4 on 2024-04-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_bonus_organic_alter_product_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organic',
            name='types',
            field=models.ManyToManyField(to='product.types'),
        ),
    ]
