# Generated by Django 5.0.4 on 2024-04-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_organic_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='testiminial',
            name='image',
            field=models.ImageField(default=1, upload_to='product/testiminial/'),
            preserve_default=False,
        ),
    ]
