# Generated by Django 5.0.4 on 2024-04-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_testiminial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='fitured_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bonus',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bonus',
            name='price_type',
            field=models.CharField(choices=[('$', 'USD'), ('UZS', "so'm")], default='$', max_length=15),
        ),
    ]
