# Generated by Django 5.0.4 on 2024-04-25 13:28

import product.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_bonus_fitured_price_bonus_price_bonus_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='image',
            field=models.ImageField(upload_to=product.helpers.SaveMediaFiles.bonus_image_path),
        ),
        migrations.AlterField(
            model_name='organic',
            name='image',
            field=models.ImageField(upload_to=product.helpers.SaveMediaFiles.organic_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=product.helpers.SaveMediaFiles.product_image_path),
        ),
        migrations.AlterField(
            model_name='testiminial',
            name='image',
            field=models.ImageField(upload_to=product.helpers.SaveMediaFiles.testiminal_image_path),
        ),
        migrations.AlterField(
            model_name='types',
            name='image',
            field=models.ImageField(upload_to=product.helpers.SaveMediaFiles.type_image_path),
        ),
    ]
